// external/dash/components/board/common/components/Intl/Format.svelte
<script context="module">
  import { replaceVariablesInString } from "~/common/helpers";

  const getMessage = (message, values, variablesMap = {}) => {
    if (message === undefined) return;
    const parsedMessage = Object.keys(values).reduce(
      (acc, key) => acc.replace(`{${key}}`, values[key]),
      message
    );
    const replacedMessage =  replaceVariablesInString(parsedMessage, variablesMap);
    return replacedMessage;
  };
</script>

<script>
  import { getContext } from "svelte";
  import { context } from "./constants";

  export let id;
  export let values = {};
  export let defaultMessage;
  export let onlyTranslated;
  export let onlyDefault;

  let messages = {};

  const { storedTranslations, variablesMap } = getContext(context.intl);

  storedTranslations.subscribe((json) => {
    messages = json;
  });
</script>

<span>
  {#if onlyDefault}
    {getMessage(defaultMessage, values, variablesMap)}
  {:else if onlyTranslated}
    {getMessage(messages[id], values, variablesMap)}
  {:else}
    {getMessage(messages[id], values, variablesMap) || getMessage(defaultMessage, values, variablesMap)}
  {/if}
</span>

// external/dash/components/board/common/components/react-base/Intl/Format.js
import React from "react";
import { replaceVariablesInString } from "~/common/helpers";
import useIntlDetails from "./useIntl";
// const React = window.React;

const getMessage = (message, values, variablesMap = {}) => {
  if (message === undefined) return;
  const parsedMessage = Object.keys(values).reduce(
    (acc, key) => acc.replace(`{${key}}`, values[key]),
    message
  );
  const replacedMessage = replaceVariablesInString(parsedMessage, variablesMap);
  return replacedMessage;
};

export const Format = ({
  id,
  values = {},
  defaultMessage,
  onlyDefault,
  onlyTranslated,
}) => {
  const { variablesMap, translations: messages } = useIntlDetails();

  let message;
  if (onlyDefault) {
    message = getMessage(defaultMessage, values, variablesMap);
  } else if (onlyTranslated) {
    message = getMessage(messages[id], values, variablesMap);
  } else {
    message =
      getMessage(messages[id], values, variablesMap) ||
      getMessage(defaultMessage, values, variablesMap);
  }

  return <span>{message}</span>;
};

export default Format;
